version: '2'
services:
    NODE_1:
        image: db_node_controller
        container_name: node_1
        ports:
            - "5000:5000"        
        environment:
            - APP_PORT=5000
            - HOST=10.20.1.200
            - NODES=172.25.1.3:5001,172.25.1.4:5002
            - PORT=8000        
        networks:
            app_subnet:
                ipv4_address: 172.25.1.2
    NODE_2:
        image: db_node_controller
        container_name: node_2
        ports: 
            - "5001:5001"        
        environment:
            - APP_PORT=5001
            - HOST=172.25.1.101
            - NODES=172.25.1.2:5000,172.25.1.4:5002
            - NODES=172.25.1.3:5001
            - PORT=8000
        links: 
            - ARD_CONT_1  
        networks:
            app_subnet:
                ipv4_address: 172.25.1.3
    NODE_3:
        image: db_node_controller
        container_name: node_3
        ports: 
            - "5002:5002"        
        environment:
            - APP_PORT=5002
            - HOST=172.25.1.102
            - NODES=172.25.1.2:5000,172.25.1.3:5001
            - NODES=172.25.1.3:5001
            - PORT=8001
        links: 
            - ARD_CONT_1  
        networks:
            app_subnet:
                ipv4_address: 172.25.1.4
    ARD_CONT_1:
        image: ard_simulator
        container_name: ard_simulator_1
        ports: 
            - "8000:8000"        
        environment:
            - PORT=8000
            - DB_NAME=FILE1.DB   
        volumes:
            - C:\Users\Mariana\Desktop\Proyecto\data\FILE1.DB:/app/FILE1.DB
        networks:
            app_subnet:
                ipv4_address: 172.25.1.101
    ARD_CONT_2:
        image: ard_simulator
        container_name: ard_simulator_2
        ports: 
            - "8001:8001"        
        environment:
            - PORT=8001
            - DB_NAME=FILE2.DB   
        volumes:
            - C:\Users\Mariana\Desktop\Proyecto\data\FILE2.DB:/app/FILE2.DB
        networks:
            app_subnet:
                ipv4_address: 172.25.1.102
    LOAD_BALANCER:
        image: nginx
        container_name: nginx
        ports: 
            - "4050:4000" 
        volumes:
            - C:\Users\Mariana\Desktop\Proyecto\data\nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            app_subnet:
                ipv4_address: 172.25.1.200
volumes:
    logvolume01: {}
networks:
    app_subnet:
        external: true